# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | /ja-jp/training/modules/get-started-with-ai-builder-object-detection/4-check | 
    self.driver.get("https://learn.microsoft.com/ja-jp/training/modules/get-started-with-ai-builder-object-detection/4-check")
    # 2 | setWindowSize | 1520x1018 | 
    self.driver.set_window_size(1520, 1018)
    # 3 | click | css=.quiz-question:nth-child(1) .quiz-choice:nth-child(1) p | 
    self.driver.find_element(By.CSS_SELECTOR, ".quiz-question:nth-child(1) .quiz-choice:nth-child(1) p").click()
    # 4 | click | css=.quiz-question:nth-child(2) .quiz-choice:nth-child(1) p | 
    self.driver.find_element(By.CSS_SELECTOR, ".quiz-question:nth-child(2) .quiz-choice:nth-child(1) p").click()
    # 5 | click | css=.quiz-question:nth-child(3) .quiz-choice:nth-child(1) p | 
    self.driver.find_element(By.CSS_SELECTOR, ".quiz-question:nth-child(3) .quiz-choice:nth-child(1) p").click()
    # 6 | click | css=.button-filled:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".button-filled:nth-child(2)").click()
    # 7 | click | css=.margin-right-none | 
    self.driver.find_element(By.CSS_SELECTOR, ".margin-right-none").click()
    # 8 | click | css=.button-filled:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".button-filled:nth-child(2)").click()
    # 9 | click | linkText=続行 | 
    self.driver.find_element(By.LINK_TEXT, "続行").click()
  
